### ISSUE TITLE
Conan registry syntax doesn't work

### ISSUE THREAD

**Issue by oraqlle** [poac-dev/poac#761]
Current trying to use the Conan registry syntax in the `poac.toml` file but the build files as Poac tries to parse the TOML table as a string.

## Example TOML

```toml
# Other details

[dependencies]
"fmt" = { version = "9.1.0", registry = "conan-v1" }
```

## Output

```sh
poac run
   Resolving dependencies ...
Error: toml::value::as_string(): bad_cast to string
 --> poac.toml
    |
 11 | "fmt" = { version = "9.1.0", registry = "conan-v1" }
    |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ the actual type is table
```

**Comment by ken-matsui** [comment]
@oraqlle The Conan support is only on the upstream (I should have mentioned that in the readme though). Can you try building Poac from the source?

**Comment by ken-matsui** [comment]
@oraqlle Did you use Homebrew to install Poac?

**Comment by oraqlle** [comment]
@ken-matsui I started building anyway but yes I used Homebrew to install.

**Comment by ken-matsui** [comment]
@oraqlle I have created a PR for Homebrew and passed all CIs. Hope it will be merged shortly.

* https://github.com/Homebrew/homebrew-core/pull/130433

**Comment by oraqlle** [comment]
No worries @ken-matsui. I tried build by source but got a link error with libgit2.

**Comment by ken-matsui** [comment]
@oraqlle You should try the Homebrew one. It has been published.

**Comment by oraqlle** [comment]
@ken-matsui works very smoothly (tested with libfmt). However I did notice that it writes to a generic conanfile.py and I'm curious how it isolates different packages and versions so they can be used across different projects? Does it isolate dependencies like Cargo does?

**Comment by ken-matsui** [comment]
@oraqlle Unfortunately, I'm not familiar with Conan since I haven't used it before. However, we appreciate any contributions you might have. Poac is open-source software.

**Comment by oraqlle** [comment]
I'll do some digging into package isolation.
