### ISSUE TITLE
Request: More clear installation instruction for platform like Ubuntu

### ISSUE THREAD

**Issue by RishabhRD** [poac-dev/poac#789]
First of all, thanks for this great thing. I would really love to try this out. However, I spent my full day installing this on ubuntu, really struggling.

My exact problem is when I am trying to do ninja, I am getting compile time errors. Seems like it is using GCC headers instead of clang headers. TBH, I don't know how to handle this. I guess experts can do this easily, but it would be really nice if we have clear instructions for this as ubuntu is really common OS and really many people are not experts in this.

I guess this is the biggest barrier for people to use this great thing.

Thank You

**Comment by ken-matsui** [comment]
@RishabhRD Why not Homebrew, which supports Ubuntu as well? As you can see, the manual build is NOT recommended, and Linux is not supported on HEAD. https://github.com/poac-dev/poac#supported-operating-systems
