### ISSUE TITLE
Stop using C++20 modules

### ISSUE THREAD

**Issue by ken-matsui** [poac-dev/poac#793]
Use a better project structure.

---

Related to:
* https://github.com/poac-dev/poac/issues/781#issuecomment-1699572982
* https://github.com/poac-dev/poac/pull/787#issuecomment-1699573620
* https://github.com/poac-dev/poac/pull/782#issuecomment-1699573444
* https://github.com/poac-dev/poac/issues/789
* https://github.com/poac-dev/poac/issues/792

**Comment by B4mbus** [comment]
Why was that decision taken?

**Comment by wx257osn2** [comment]
I honestly agree with this decision, because currently compilers doesn't provide good support to C++20 modules. That is not production-quality but experimental for now. At least I have failed to set up the development environment.

**Comment by ken-matsui** [comment]
Yes, there is a lack of basic support for C++20 modules. Clang has already implemented [P1689R5](https://isocpp.org/files/papers/P1689R5.html). However, GCC has not yet merged the [patch series](https://gcc.gnu.org/pipermail/gcc-patches/2023-July/623414.html). This decision will not affect the support plan that Poac builds a project that use modules. Just for Poac itself, C++20 modules will not be used.
