### ISSUE TITLE
compile_commands.json generation?

### ISSUE THREAD

**Issue by Singha360** [poac-dev/poac#796]
For some people who are using `clangd` as their language server. Is it possible to have poac generate a `compile_commands.json` file since that is required for clangd to locate all the includes?

Is this planned for the future?

**Comment by ken-matsui** [comment]
It is already implemented https://github.com/poac-dev/poac/pull/767.

**Comment by Singha360** [comment]
This doesn't seem to be working on Mac? From what I understand it is supposed to be generated automatically based on the discussion [here](https://github.com/orgs/poac-dev/discussions/763)

I am using:

macOS: 13.5.2
Ninja: 1.11.1

<img width="270" alt="image" src="https://github.com/poac-dev/poac/assets/35334787/7467111c-5a3d-4fc7-98d4-cce784c4f59c">

**Comment by ken-matsui** [comment]
@Singha360 I think your installed Poac version is 0.6.0. IIRC, this feature is currently only available upstream.

**Comment by Singha360** [comment]
Oh yeah that's my fault, thanks!

**Comment by SunPodder** [comment]
I'm on `poac 0.9.3`. I think with the new codes this feature is broken again?

**Comment by ken-matsui** [comment]
Yes, Poac currently does not generate the compilation database automatically. Instead, we should use `--compdb`. Since compilation commands differ by mode, `compile_commands.json` will be generated within `poac-out/${mode}`. I think the current interface is stable. @SunPodder, thank you for your information.

```console
$ poac build -h
Compile a local package and all of its dependencies

Usage: poac build [OPTIONS]

Options:
...
  -h, --help          Print help
  -d, --debug         Build with debug information [default]
  -r, --release       Build with optimizations
      --compdb        Generate compilation database instead of building
...

$ poac build --compdb
 Generated poac-out/debug/compile_commands.json

$ poac build -r --compdb
 Generated poac-out/release/compile_commands.json
```
