### ISSUE TITLE
Failing to build when installing from AUR (ver. 0.2.1)

### ISSUE THREAD

**Issue by lukakralik** [poac-dev/poac#815]
Cloning from github and building with make works fine. AUR installation runs into 6 errors:

1. build.hpp:166:33: error: loop variable ‘o’ creates a copy from type ‘const std::__cxx11::basic_string<char>’ [-Werror=range-loop-construct]
  166 |                 for (const auto o : *obj_files_path) {
                                       ^
2. init.hpp:23:43: error: ‘std::string boost::filesystem::basename(const path&)’ is deprecated: Use path::stem() instead [-Werror=deprecated-declarations]
   23 |             std::string tmp = fs::basename(s);
      |                               ~~~~~~~~~~~~^~~

3. publish.hpp:33:64: error: ‘std::string boost::filesystem::basename(const path&)’ is deprecated: Use path::stem() instead [-Werror=deprecated-declarations]
   33 |          const fs::path copy_file = temp_path / fs::basename(project_dir);
      |                                                 ~~~~~~~~~~~~^~~~~~~~~~~~~

4. net.hpp:232:24: error: no matching function for call to ‘boost::beast::http::message<true, boost::beast::http::empty_body, boost::beast::http::basic_fields<std::allocator<char> > >::set(boost::beast::http::field, std::size_t)’
  232 |                 req.set(http::field::content_length, body.content_length());
      |                 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

5. net.hpp:375:69: error: ‘const boost::beast::string_view’ {aka ‘const class boost::core::basic_string_view<char>’} has no member named ‘to_string’

6. error: ‘const boost::beast::string_view’ {aka ‘const class boost::core::basic_string_view<char>’} has no member named ‘to_string’

**Comment by ken-matsui** [comment]
@lukakralik It is too old since I do not maintain it. You may want to update the AUR package by yourself or contact the publisher. https://github.com/poac-dev/poac/issues/195
