### ISSUE TITLE
Different filetypes

### ISSUE THREAD

**Issue by JeromeSchmied** [poac-dev/poac#822]
Hi, great project!
I wonder how I use `.cxx` or `.cpp` instead of `.cc`, because those I prefer more.

Thanks in advance!

**Comment by ken-matsui** [comment]
@JeromeSchmied 

Other than `src/main.cc`, you can use any file extensions defined here:

https://github.com/poac-dev/poac/blob/022bd3f66a172db74819b9e0f3ab34c7f5cf5130/src/BuildConfig.hpp#L5-L10
