### ISSUE TITLE
cmd poac add not working

### ISSUE THREAD

**Issue by solfrak** [poac-dev/poac#917]
# Software Version
poac 0.9.3 (11014aa 2024-02-03)

# Expected Behavior
following the readme, I should be able to add a dependency as follow:
`poac add libgit2 --sys --version "1.1.0"`

# Error:
```
Error: unexpected argument 'add' found

For a list of commands, try 'poac help'
```

**Comment by ken-matsui** [comment]
@solfrak Please see: https://github.com/poac-dev/poac/commit/ec82382649a18dc2603d56c79a48ef0c5b159b55
