### ISSUE TITLE
Depedency name must be alphanumeric

### ISSUE THREAD

**Issue by iErik** [poac-dev/poac#921]
I'm trying to use the `gtkmm-4.0` in a project but the issue is that the package name (at least in arch linux) has a dot (`.`) in it, so even though pkg-config is able to find it just fine, poac doesn't seem to like that:
![image](https://github.com/poac-dev/poac/assets/3172683/9d252ef3-eb6a-474a-b3f9-1b2766f243fe)
![image](https://github.com/poac-dev/poac/assets/3172683/b15c86f0-fa4e-458f-8e31-82c914a87154)
![image](https://github.com/poac-dev/poac/assets/3172683/20ab261d-ae41-4938-856a-2abb6ff72f7d)

How can this be fixed?
This is Poac version `0.9.3` btw

**Comment by iErik** [comment]
Thank you very much! :)

**Comment by yaito3014** [comment]
It seems that ncurses, very common library, often provides `ncurses++.pc` or `ncurses++w.pc`, so we might be better to consider these `++` patterns; I guess.

**Comment by iErik** [comment]
Alright, that's reasonable. No rush 😄
