### ISSUE TITLE
Incorrect CXX value in internally generated Makefile

### ISSUE THREAD

**Issue by watiko** [poac-dev/poac#924]
In the Makefile generated by poac when the CXX environment variable is not specified, CXX is specified as follows.

```Makefile
CXX ?= clang++
# https://github.com/poac-dev/poac/blob/0.9.3/src/BuildConfig.cc#L569
```

In this case, CXX is Implicit Variables in Gnu Make, so the default value of `g++` is retained. This means that unintentional use of `g++` will occur via make when CXX environment variables are not specified.
https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

I'm not familiar with make, but the following might work as intended.

```Makefile
ifeq "$(origin CXX)" "default"
	CXX := clang++
endif

.PHONY: all
all:
	@echo "$(info $(CXX))"

```

**Comment by ken-matsui** [comment]
@watiko  Thank you for reporting this!  Would you want to submit a PR for this?  I'm happy to review it.
