### ISSUE TITLE
Build Error: 'git_error_clear' Not Declared in 'git2::Exception::Exception()'

### ISSUE THREAD

**Issue by kxrxh** [poac-dev/poac#930]
Hello,

I've encountered a build error while compiling the latest version of Poac (also I tried 0.9.2). I got this:

```
g++ -std=c++20 -fdiagnostics-color -pedantic-errors -Wall -Wextra -Wpedantic -g -O0 -DDEBUG -MMD -DPOAC_PKG_VERSION='"0.9.2"' -DPOAC_COMMIT_HASH='""' -DPOAC_COMMIT_SHORT_HASH='""' -DPOAC_COMMIT_DATE='""' -isystem build-out/DEPS/toml11    -c src/Git2/Exception.cc -o build-out/Git2/Exception.o
src/Git2/Exception.cc: In constructor ‘git2::Exception::Exception()’:
src/Git2/Exception.cc:28:5: error: ‘git_error_clear’ was not declared in this scope; did you mean ‘git_error_last’?
   28 |     git_error_clear();
      |     ^~~~~~~~~~~~~~~
      |     git_error_last
make: *** [Makefile:53: build-out/Git2/Exception.o] Error 1
```

**Steps to Reproduce:**

1. Clone the latest version of Poac from the repository.
2. Run the build command: `make`.

**Solution**
I renamed 'git_error_clear' to 'git_error_last' and the build was successful, but I don't think it was the right way to solve that problem.

**Comment by yaito3014** [comment]
It seems libgit2 suddenly moved `git_error_clear`'s declaration to another header in version 1.8 https://github.com/libgit2/libgit2/commit/f78ae89bf1800444257160ad6ca48a0cd95384ba and this causes the error.

**Comment by ken-matsui** [comment]
Looks like dropping the later versions support would be better, as they don't follow SemVer.

**Comment by ken-matsui** [comment]
I believe this issue has been resolved. Please feel free to reopen it if it persists.
