### ISSUE TITLE
Error: unexpected argument 'add' found

### ISSUE THREAD

**Issue by kseou** [poac-dev/poac#936]
**Certify that you tried to find the same problem** (this is important for us to reduce workload)
- [X] I certify that I looked for the same issue and couldn't find it to the best of my knowledge.

**Describe the bug**
Readme states that you can now run `poac add` to add dependencies, however. When running `poac add` I'm getting the following:

```
> poac add
Error: unexpected argument 'add' found
```

**To Reproduce**
Run `poac add` command

**Expected behavior**
As explained in the documentation when adding a dependency.

**Screenshots**
![image](https://github.com/poac-dev/poac/assets/162237002/a8c68358-5282-4690-8484-024581de36b2)

**Desktop (please complete the following information):**
macOS Sonoma 14.5 - Studio M2 Max

**Additional context**
N/A

**Comment by ken-matsui** [comment]
https://github.com/poac-dev/poac/issues/917

**Comment by kseou** [comment]
I’m sorry, but what am I to see in that report? The only thing that is linked is the README?

**Comment by ken-matsui** [comment]
@kseou Since you are using `0.9.3`, you should see https://github.com/poac-dev/poac/blob/0.9.3/README.md, which does not consist of `poac add`.

**Comment by ken-matsui** [comment]
And this is stated at the top of the current README:

> [!IMPORTANT]
> The information here may vary depending on the version you are using.  Please refer to the corresponding `README.md` by visiting the Git tag corresponding to your version, e.g., https://github.com/poac-dev/poac/blob/0.9.3/README.md.  Running `poac version` will provide you with the current version.

**Comment by kseou** [comment]
> @kseou Since you are using `0.9.3`, you should see https://github.com/poac-dev/poac/blob/0.9.3/README.md, which does not consist of `poac add`.

I'm a little bit confused as to why is it in a documentation with the latest release of poac (currently available version is 0.9.3) if it's not in the software, why include the mention of a feature that doesn't exist yet? It really confuses people.


> And this is stated at the top of the current README:
> 
> Important
> 
> The information here may vary depending on the version you are using. Please refer to the corresponding `README.md` by visiting the Git tag corresponding to your version, e.g., https://github.com/poac-dev/poac/blob/0.9.3/README.md. Running `poac version` will provide you with the current version.

While it is not in text, it is in my screenshot provided.

**Comment by ken-matsui** [comment]
> > @kseou Since you are using `0.9.3`, you should see https://github.com/poac-dev/poac/blob/0.9.3/README.md, which does not consist of `poac add`.
> 
> I'm a little bit confused as to why is it in a documentation with the latest release of poac (currently available version is 0.9.3) if it's not in the software, why include the mention of a feature that doesn't exist yet? It really confuses people.

Because it's the main branch.

> 
> > And this is stated at the top of the current README:
> > Important
> > The information here may vary depending on the version you are using. Please refer to the corresponding `README.md` by visiting the Git tag corresponding to your version, e.g., https://github.com/poac-dev/poac/blob/0.9.3/README.md. Running `poac version` will provide you with the current version.
> 
> While it is not in text, it is in my screenshot provided.

I don't quite understand what you mean.

**Comment by kseou** [comment]
poac version is added to the report in a screenshot

**Comment by ken-matsui** [comment]
I know, that's why I suggested you take a look at https://github.com/poac-dev/poac/blob/0.9.3/README.md
