### ISSUE TITLE
Installation error - paru for Arch Linux - Version 0.9.3-1

### ISSUE THREAD

**Issue by shyamsundarb-arch** [poac-dev/poac#937]
**Certify that you tried to find the same problem on [Issues](https://github.com/poac-dev/poac/issues), [PRs](https://github.com/poac-dev/poac/pulls), and [Discussions](https://github.com/orgs/poac-dev/discussions)** (this is important for us to reduce workload)
- [Y ] I certify that I looked for the same issue and couldn't find it to the best of my knowledge.

**Describe the bug**
When installing poac via AUR (paru) for Arch linux, I get errors and the installation fails. 

**To Reproduce**
Run the following command
```
paru -S poac
```
Choose option 1, i.e., "poac". 

**Expected behavior**
poac to be compiled and installed.

**Screenshots**
![image](https://github.com/poac-dev/poac/assets/6845982/98eb45f0-6ecf-45f5-a398-40b6f9a61067)

**Environment (please complete the following information):**
 - OS: Arch Linux (x64) 
 - Poac Version 0.9.3-1
- Package Manager - paru (AUR)
- 
**Additional context**
NA

**Comment by shyamsundarb-arch** [comment]
I cloned the repo to local and tried to ```make``` the project. It succeeds. However, the local clone build uses g++ rather clang++ which the paru install command used to compile this package.
![image](https://github.com/poac-dev/poac/assets/6845982/7bc4cfed-9be2-4d50-9de8-2ff9b77a93b5)

**Comment by yaito3014** [comment]
duplicate. #930 #935

**Comment by shyamsundarb-arch** [comment]
oops, didn't realise both were same. Will close this duplicate.
