### ISSUE TITLE
セルフホストできない

### ISSUE THREAD

**Issue by wx257osn2** [poac-dev/poac#98]
[パッケージリポジトリ](https://poac.io/packages)に `poac` の依存パッケージが存在しないため， `poac` に対して `poac install` を行うとコケる．

## 不足パッケージ
- [ ] `boost/property_tree`
- [ ] `boost/filesystem`
- [ ] `boost/range`
- [ ] `boost/algorithm`
- [ ] `boost/foreach`
- [ ] `boost/dynamic_bitset`
- [ ] `boost/beast`
- [x] ~`cpp-shell-cmd`~

**Comment by matken11235** [comment]
パッケージ頑張ります (成果報告会が終わったら...)
`cpp-shell-cmd`は依存関係から削除しました．-> d621f5df5afe2a41d70a740c04409b656fa1f619

**Comment by wx257osn2** [comment]
こう，#93 でCygwinユーザー向けのビルドができることは確認したけど，たぶん現状だとpoacでセルフホストしようとしたときにコケる(はずな)ので，パッケージが揃えば確認と修正ができるなぁという…  
当座CMake使ってビルドできればそれで良い，ということであればREADMEにCygwinユーザー向けの注釈を加えるPRを飛ばします．(これは本質的な解決ではないですし，Cygwinを積極的にサポートするのかは存じませんが…)

**Comment by matken11235** [comment]
とりあえずは，最終的にはバイナリ配布を行う予定なのでCMakeでビルドできればそれで良いと思っています．
ですので，PR頂けるのは非常にありがたいです！

**Comment by wx257osn2** [comment]
#100 で追記のPR飛ばしました．
