### ISSUE TITLE
[feature] clangd

### ISSUE THREAD

**Issue by JeromeSchmied** [poac-dev/poac#982]
**Certify that you tried to find the same problem on [Issues](https://github.com/poac-dev/poac/issues), [PRs](https://github.com/poac-dev/poac/pulls), and [Discussions](https://github.com/orgs/poac-dev/discussions)** (this is important for us to reduce workload)
- [x] I certify that I looked for the same issue and couldn't find it to the best of my knowledge.

**Describe the bug**
`clangd` doesn't recognize added dependencies

**To Reproduce**
1. add a dependency, eg.: [cpptui](https://github.com/csboo/cpptui)
2. open up `src/main.cc` with an editor that supports `clangd`, eg.: `neovim`
3. add the dependency's header file (in my case it's `#include <tui.hpp>`) and there is the error from `clangd` stating: `tui.hpp not found (pp_file_not_found)`

**Screenshots**
![image](https://github.com/user-attachments/assets/3df342a5-b365-47a0-8bc0-f141d31e6fdc)

**Expected behavior**
Well, it would be nice to tell `clangd` which paths are included at compile-time, then it'd know about the dependencies, could do `goto-definition` and stuff.

**Possible implementation ideas**
create a `.clangd` or a `compile_commands.json` for the purpose, and when adding a new dependency, append that to the list of the `-I`

**Workaround**
for me, the solution was: a `.clangd` file with the following content:
```yml
# .clangd
CompileFlags:
  Add: [-I/home/user/.cache/poac/git/src/cpptui]
```
after this, it works just as expected
> **_note_**: I've had to use a full path, stuff like `~` or `*` did not solve the problem

**Environment:**
 - OS: [Arch Linux btw]
 - Poac Version [`poac 0.10.0 (b912957 2024-08-12)`]
 - shell: [`fish, version 3.7.1`]
 - editor: [`helix 24.7`]
 - clangd: [`clangd version 18.1.8 Features: linux Platform: x86_64-pc-linux-gnu`]

**Comment by JeromeSchmied** [comment]
I guess [Bear](https://github.com/rizsotto/bear) would be able to help here.

**Comment by ken-matsui** [comment]
We can generate `compile_commands.json`, but didn't it work as intended?

```
$ poac build --compdb
 Generated poac-out/debug/compile_commands.json
```

**Comment by JeromeSchmied** [comment]
yes, it did, I just didn't know about it, thank you!

**Comment by ken-matsui** [comment]
Great to hear!
